# Generated by Django 5.0.3 on 2024-03-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_post_magnitudemw_post_file2_post_file3_post_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file2',
        ),
    ]
