# Generated by Django 5.0.3 on 2024-03-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_remove_post_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file2',
            field=models.FileField(blank=True, upload_to='sac'),
        ),
    ]
