# Generated by Django 5.0.3 on 2024-03-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0004_post_file2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
