# Generated by Django 5.0.3 on 2024-06-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0006_post_magnitudemw'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file3',
            field=models.FileField(blank=True, upload_to='data2'),
        ),
    ]
