# Generated by Django 5.0.3 on 2024-06-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0007_post_file3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='MagnitudeMW',
        ),
    ]
