# Generated by Django 3.2.19 on 2024-06-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0007_post_file3'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test111',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
