# Generated by Django 5.0.3 on 2024-06-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0009_post_magnitudemw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file3',
        ),
    ]
