# Generated by Django 5.0.6 on 2024-06-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0008_post_test111'),
        ('testdb', '0010_remove_post_file3'),
    ]

    operations = [
    ]
