# Generated by Django 5.0.6 on 2024-06-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0011_merge_0008_post_test111_0010_remove_post_file3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='test111',
            new_name='test11',
        ),
    ]
