# Generated by Django 5.0.6 on 2024-06-18 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0012_rename_test111_post_test11'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test11',
        ),
    ]
