# Generated by Django 5.0.6 on 2024-06-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0014_post_test11'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file3',
            field=models.FileField(blank=True, upload_to='data2'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, default='default1.jpg', upload_to='image_ml'),
        ),
    ]
