# Generated by Django 5.0.6 on 2024-06-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0018_post_magnitudemw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='MagnitudeMW',
        ),
        migrations.AddField(
            model_name='post',
            name='aaaaaaaa',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
