# Generated by Django 5.0.6 on 2024-06-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0019_remove_post_magnitudemw_post_aaaaaaaa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='aaaaaaaa',
        ),
        migrations.AddField(
            model_name='post',
            name='MagnitudeMW',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
