# Generated by Django 5.0.6 on 2024-06-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0020_remove_post_aaaaaaaa_post_magnitudemw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='MagnitudeMW',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
