# Generated by Django 5.0.6 on 2024-09-16 21:25

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0022_remove_post_magnitudemw_post_magnitudemw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(default='', upload_to='data')),
                ('file1_data', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200000), blank=True, default=list, size=None)),
                ('file11', models.FileField(default='', upload_to='data')),
                ('file11_data', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200000), blank=True, default=list, size=None)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
