# Generated by Django 5.0.6 on 2024-09-16 23:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0023_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file1',
            field=models.FileField(default='', upload_to='data'),
        ),
        migrations.AddField(
            model_name='post',
            name='file11',
            field=models.FileField(default='', upload_to='data'),
        ),
        migrations.AddField(
            model_name='post',
            name='file11_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200000), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='post',
            name='file1_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200000), blank=True, default=list, size=None),
        ),
        migrations.DeleteModel(
            name='ML',
        ),
    ]
