# Generated by Django 5.0.6 on 2024-09-20 01:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0025_remove_post_file11_data_remove_post_file1_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='DIS_m2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='amp_m2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='azm_m2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='b_azm_m2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='comp_m2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='gain_m2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='local_m_m2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='station_m2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
    ]
