# Generated by Django 5.0.6 on 2024-09-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0027_alter_post_dis_m2_alter_post_amp_m2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_h',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='image_maps'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_p',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='image_maps'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_z',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='image_maps'),
        ),
    ]
