# Generated by Django 5.0.6 on 2024-09-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0028_post_image_h_post_image_p_post_image_z'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='image_maps'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_h',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='image_ml'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_p',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='image_ml'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_z',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='image_ml'),
        ),
    ]
