# Generated by Django 5.0.6 on 2024-09-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0029_remove_post_image2_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, default='default1.jpg', upload_to='image_ml'),
        ),
    ]
