# Generated by Django 5.0.6 on 2024-09-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0030_post_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='image_ml'),
        ),
    ]
